name: CI

on:

  pull_request:
    branches: ["main", "dev/*"]

  push:
    branches: ["main", "dev/*"]

jobs: 

  unit:
    uses: ./.github/workflows/unit.yaml

  notebooks:
    uses: ./.github/workflows/notebook_smoke.yaml
